"use client"
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Header from './components/header';
import theme from './theme';
import { ThemeProvider } from '@mui/material';
import { MyContextProvider } from './context/store';

// const inter = Inter({ subsets: ["latin"] });


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang='en' >
      <body className={`min-h-screen px-[46px] py-[26px] bg-white`}>
        <ThemeProvider theme={theme}>
          <MyContextProvider>
            <Header />
            {children}
          </MyContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}


// "use client";

// import Footer from "@/components/Footer";
// import Header from "@/components/Header";
// import ScrollToTop from "@/components/ScrollToTop";
// import { Inter } from "next/font/google";
// import "node_modules/react-modal-video/css/modal-video.css";
// import "../styles/index.css";

// const inter = Inter({ subsets: ["latin"] });

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html suppressHydrationWarning lang="en">
//       {/*
//         <head /> will contain the components returned by the nearest parent
//         head.js. Find out more at https://beta.nextjs.org/docs/api-reference/file-conventions/head
//       */}
//       <head />
//       <body className={`bg-[#FCFCFC] dark:bg-black overflow-x-hidden w-full`}>
//         <Providers>
//           <div className="flex flex-col justify-between min-h-[100vh]">
//             <Header />
//             <div className="flex flex-col items-center justify-center min-h-[38vh] h-fit mt-[15vh]">
//               {children}
//             </div>
//             <Footer />
//             <ScrollToTop />
//           </div>
//         </Providers>
//       </body>
//     </html>
//   );
// }
